const genreList = [
    'Action',
    'Adventure',
    'Adventure',
    'Adventure fiction',
    'Biography',
    'Comedy',
    'Comedy horror',
    'Coming-of-age story',
    'Dark comedy',
    'Detective fiction',
    'Drama',
    'Espionage',
    'Fairy tale',
    'Farce',
    'Fantasy',
    'Fantasy',
    'Fiction',
    'Film criticism',
    'Historical Fiction',
    'Historical drama',
    'History',
    'Horror',
    'Humor',
    'High fantasy',
    'Hybrid genre',
    'Magical Realism',
    'Melodrama',
    'Mystery',
    'Mystery',
    'Narrative',
    'Police procedural',
    'Review',
    'Romance',
    'Romantic comedy',
    'Satire',
    'Science fiction',
    'Screenplay',
    'Slapstick',
    'Superhero fiction',
    'Suspense',
    'Thriller',
    'Tragedy',
    'Western',
    'Other'
];


export default genreList